### ISSUE TITLE
User map isn't saved to local storage if a link is shared (until reload)

### ISSUE THREAD

**Issue by raphaellaude** [districtr/districtr-v2#143]
This is an odd case and probably not worth solving for or else is v low priority. But figured I'd report it anyway. If we end up going with the local store as the permanent place to store user maps then we should probably fix this, though.

**Comment by nofurtherinformation** [comment]
This is probably something in the [query params observer](https://github.com/districtr/districtr-v2/blob/358a37e676df53e4aa8fb93cc3c192b0301e777f/app/src/app/utils/api/queryParamsListener.ts#L27) like `useMapStore.getState.upcertUserMap({...config})`

**Comment by nofurtherinformation** [comment]
I believe this is resolved
