### ISSUE TITLE
Mouseenter event to keep painting

### ISSUE THREAD

**Issue by nofurtherinformation** [districtr/districtr-v2#188]
If you are painting, move your cursor off of the map or map layers, then return, while still clicked, the map does not continue to paint as you would expect

**Comment by raphaellaude** [comment]
Fixed by #182, no @nofurtherinformation ?

**Comment by nofurtherinformation** [comment]
This is slightly subtly the opposite problem -- there are some cases where the application is too quick to cut off a paint even
