### ISSUE TITLE
Persist list of user maps

### ISSUE THREAD

**Issue by raphaellaude** [districtr/districtr-v2#40]
Allow users to return to maps they were working on in a more ergonomic way than copy-pasting their `document_id` from the URL to a sticky note.

This feature could be achieved either by
- Setting an anonymous `user_id` in cookies / local storage and creating a table in the db with `(user_id, document_id)` entries, along with an endpoint to fetch those
- Storing a list of `document_id`s in local storage

**Comment by nofurtherinformation** [comment]
Initial implementation of this in #127
