### ISSUE TITLE
Map sometimes fails to pull document assignments from backend on load

### ISSUE THREAD

**Issue by raphaellaude** [districtr/districtr-v2#41]
Still investigating when and why this happens. Seems to be slightly inconsistent.

**Comment by bailliekova** [comment]
1) Front end needs to know what doc it's working with
2) Front end needs to have initialized the map 

These things mostly work right now, timing wise, but it's not guaranteed.

**Comment by bailliekova** [comment]
Existing linked PR made things worse, womp womp.

**Comment by nofurtherinformation** [comment]
@bailliekova @raphaellaude I'm having trouble replicating this issue on my local dev environment or on the dev fly deployment -- any advice on conditions that generate this issue?

**Comment by bailliekova** [comment]
we have a few sentry logs but I also haven't been able to replicate- @raphaellaude may have insights

**Comment by raphaellaude** [comment]
It seems like it has mostly been working... I'll re-read the code and check if it is still possible that the map loads but a user's existing assignments aren't painted.

**Comment by raphaellaude** [comment]
Closing this as I haven't seen it in a while
