### ISSUE TITLE
Fly to gerryDB view bounds on layer change

### ISSUE THREAD

**Issue by raphaellaude** [districtr/districtr-v2#61]
The bounds and zoom level should probably be stored in DB and sent to client with the gerryDB view information.

TBD
- Are those bounds generated on the fly?
- Are they precomputed?
- That info can be created as part of the tile creation probably – just do it once and then never think of it again
- When creating tiles there might be a tile stats flag, could use that

**Comment by mariogiampieri** [comment]
strong preference for pre-computing and storing the `bounds` as a property of each view:
- `fgb_stats = subprocess.run(ogrinfo -json -so name_of_view.fgb)` where `fgb_stats["layers"][0]["geometryFields"]["extent"]` is the bounds of the layer
- in the frontend, we can call `map.fitBounds(gerryView.extent)` to zoom to the layer properly

**Comment by bailliekova** [comment]
Needed for end-user testing

**Comment by raphaellaude** [comment]
Migration should backfill the location for existing `districtr` maps

**Comment by mariogiampieri** [comment]
closed via #147
