### ISSUE TITLE
Render full geometries at high zoom levels

### ISSUE THREAD

**Issue by raphaellaude** [districtr/districtr-v2#70]
See![image](https://github.com/user-attachments/assets/a37d5385-ec56-4561-8695-61dd0d9f5290)

**Comment by mariogiampieri** [comment]
in a similar vein- after shattering is implemented, are we assuming users will only be able to paint blocks at a certain zoom level or within a certain set of parent geometries? because if so, we should simplify tiles at lower zoom levels to increase speed.

**Comment by nofurtherinformation** [comment]
This issue is still active. To be prioritized after BVAP ahead of user testing! cc @raphaellaude
